# Generated by Django 4.1.7 on 2023-04-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('image', models.CharField(max_length=1200)),
                ('release_date', models.CharField(max_length=30)),
                ('lte_exests', models.BooleanField()),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
    ]
